{% set name = "dvc-task" %}
{% set version = "0.40.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 909af541bf5fde83439da56c4c0ebac592af178a59b702708fadaacfd6e7b704

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - celery >=5.3.0,<6
    - funcy >=1.17
    - kombu
    - python >={{ python_min }}
    - pywin32-on-windows
    - shortuuid >=1.0.8
  run_constrained:
    - pywin32 >=225

test:
  imports:
    - dvc_task
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/iterative/dvc-task
  summary: Extensible task queue used in DVC.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - karajan1001
    - pmrowla
    - efiop
    - shcheklein
    - skshetry
