{% set name = "dvc-task" %}
{% set version = "0.40.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: eacbc2d1cacbe8a93067fbef5922ff84ead8bb2c3768541c3e32dab40d7b1b83

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - celery >=5.3.0,<6
    - funcy >=1.17
    - kombu
    - python >=3.7
    - pywin32-on-windows
    - shortuuid >=1.0.8
  run_constrained:
    - pywin32 >=225

test:
  imports:
    - dvc_task
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iterative/dvc-task
  summary: Extensible task queue used in DVC.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - karajan1001
    - pmrowla
    - efiop
    - shcheklein
    - skshetry
